---
- hosts: all
  become: yes
  tasks:

 # touch the same file, but add/remove some permissions
- name: touch the same file
  file:
    path: /home/ansible/foo.conf
    state: touch
    mode: "u+rw,g-wx,o-rwx"
       
  
- name: for command get 2 IDEOPOTENT
  command: mv /home/ansible/foo.conf  /home/ansible/foo.dis
    creates: /home/ansible/foo.dis