---
- hosts: all
  become: yes
  tasks:

 # touch the same file, but add/remove some permissions
- name: for command get 2 IDEOPOTENT
  command: mv /home/ansible/foo.conf  /home/ansible/foo.dis
  creates: /home/ansible/foo.dis