---
- hosts: all
  become: yes
  vars:
    debugaval1: register data
    debugaval2: set facts
  gather_facts: yes
  tasks:
  - name: install basic software for devlopments for redhat
    yum:
      name: "{{ item }}"
    with_items:
      - git
      - tree
      - wget
    ignore_errors: yes
    when: ansible_os_family =="RedHat"
  - name: install basic software for devlopments for debian
    apt:
      name: "{{ item }}"
    with_items:
      - git
      - tree
      - wget
    ignore_errors: yes
    when: ansible_os_family =="Debian"
    tags: genralsoft
  - name: install httpd on redhat
    yum:
      name: "{{ redhatwebserver }}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: deployindex of httpd
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify:  httpdrestart
    when: ansible_os_family =="RedHat"
    tags: httpdserver
  - name: install apache2 on ubuntu
    apt:
      name: "{{ubuntuwervserver}}"
      state: present
    register: reg_apache_result
    notify: apacherestart
    when: ansible_os_family =="Debian"
  - name: deployindex of apache2
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify:  httpdrestart
    when: ansible_os_family =="Debian"
    tags: apacherestart
  - name:  dispaly the "{{ debugaval1 }}" 
    debug:
      msg: "{{ reg_apache_result }}"

  - name:  dispaly the "{{ debugaval2 }}" 
    set_fact: 
      set_facttest:  set fact vali is "{{ redhatwebserver }}"  
    when: ansible_os_family =="RedHat"
     
  - name:  dispaly the "{{ debugaval2 }}" 
    set_fact: 
      set_facttest:  set fact vali is "{{ redhatwebserver }}"  
    when: ansible_os_family =="Debian"  
  
  - name:  dispaly the set_facttest values" 
    debug:
      msg: "{{ set_facttest }}"
  - name: file create 
    file: 
      path: /home/ansible/ansible.txt
      state: touch
      mode: 0777
  - name: copy passwd file file
    copy:
      src: /home/ansible/ansible.txt
      dest: /etc/passwd

  handlers:
  - name: httpdrestart
    service:
      name: httpd
      state: restarted
  - name: apacherestart
    service:
      name: apache2
      state: present
  
       




  

