---
# tasks file for tom8.deploy
  

- name: Download QTtapti-1.0 war file
  get_url:
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /opt/tomcat/apache-tomcat-8.0.51/webapps/
    force_basic_auth: yes
  notify: tomcatrestartd

