---
# tasks file for tom8.java
- name: install  java on redhat {{ javaversion_rehaht7 }}
  yum:
    name: "{{ javaversion_rehaht7 }}"
    state: present
  when: ansible_os_family =="RedHat"

- name: install  java on ubuntu {{ javaversion_ubuntu14 }}
  apt:
    name: "{{ javaversion_ubuntu14 }}"
    state: present
  when: ansible_os_family =="RedHat"